fetch_users_job:
  cron: "*/60 * * * *"  # Run every 1 hour
  class: "FetchUsersJob"
  queue: default

process_users_job:
  cron: "0 0 * * *"  # Run once a day at midnight
  class: "ProcessDailyStatsJob"
  queue: default
